[package]
name = "day_5"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports", "plotters"]}

[[bench]]
name = "my_bench"
harness = false
