[package]
name = "day_6"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports", "plotters"]}

[[bench]]
name = "benches"
harness = false
