[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.4"

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports", "plotters"]}

[[bench]]
name = "my_bench"
harness = false
